# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: "2.2"

services:
  node-backend:
    image: node:18
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - $PWD:/home/node/app:cached
    # ports:
    #   - "8180:8180"
    command: "npm install -g node-gyp && npm run install"
    # command: ["sh", "-c", "npm install && npm run build"]
